### ISSUE TITLE
Error while crafting new app

### ISSUE THREAD

**Issue by manshu** [unicodeveloper/laravel-hackathon-starter#17]
[GuzzleHttp\Exception\ClientException]
  Client error: `GET http://goodheads.io/larathon.zip` resulted in a `404 Not
   Found` response:
  <!DOCTYPE html>
  
  <!--[if IE (truncated...)

**Comment by unicodeveloper** [comment]
Sorry about that, I'll fix that in a bit @manshu

**Comment by unicodeveloper** [comment]
I have updated the hackathon installer, so you can just do `composer global require unicodeveloper/hackathon-installer=1.0.2` or do `composer global remove unicodeveloper/hackathon-installer` and then install it again by `composer global require unicodeveloper/hackathon-installer`

**Comment by manshu** [comment]
Perfect, i'll work on it tomorrow. thanks for the help.
