### ISSUE TITLE
Docs: note about pgsql being the default driver

### ISSUE THREAD

**Issue by ProfNandaa** [unicodeveloper/laravel-hackathon-starter#19]
This will help those using other DBs other that Postgres, I was getting an error when running migrations.
```
[PDOException]         
could not find driver
```

I had to add this line on the `.env`:
```
DB_CONNECTION=mysql
```

**Comment by unicodeveloper** [comment]
Thanks, someone also had this issue some time back. I'll be super glad if you could raise a PR that states this in the doc @ProfNandaa

**Comment by ProfNandaa** [comment]
Will be on that sir @unicodeveloper
