### ISSUE TITLE
Multiple Oauth accounts create multiple users

### ISSUE THREAD

**Issue by necrogami** [unicodeveloper/laravel-hackathon-starter#25]
If you attach multiple oauth adapters and try signing into an account say github and bitbucket. Even if your details (email name) are the same it will generate 2 separate accounts on the site instead of linking them together.

**Comment by necrogami** [comment]
Also there's no way to link an oauth account to an existing created account

**Comment by unicodeveloper** [comment]
PRs are always welcome 😊

**Comment by necrogami** [comment]
Due to the nature of how the oauth tokens are stored this is going to most likely require a major re-write of how oauth is stored and linked to user accounts. Which is going to be a 1 to many relationship. Also upon logging in without a linked email address needs to ask someone to create an account or link an existing account.

**Comment by unicodeveloper** [comment]
I have added labels to this. I might work on this but I'm not promising right away because I'm busy at the moment...but if you want to help, you can take a stab at it and we'll review together 😊

**Comment by necrogami** [comment]
I'm looking into it.

**Comment by acekyd** [comment]
I'll be watching from the sidelines

**Comment by rohmanmuhamad** [comment]
Waiting for your patch.
